# This override file should be used when running this service in isolation
# to provide dependencies and expose ports for local testing

services:
  ffc-sfd-auth:
    build:
      target: development
    image: ffc-sfd-auth-development
    container_name: ffc-sfd-auth-development
    ports:
      - "3002:3002"
      - "9002:9229"
    volumes:
      - ./app:/home/node/app
      - ./package.json:/home/node/package.json

  ffc-sfd-auth-redis:
    ports:
      - "6302:6379"
    volumes:
      - redis_data:/data
    command: redis-server --dir /data --save 5 1

volumes:
  redis_data:
