services:
  ffc-sfd-auth:
    build:
      context: .
      target: production
    image: ffc-sfd-auth
    container_name: ffc-sfd-auth
    environment:
      APPINSIGHTS_CLOUDROLE: ffc-sfd-auth-local
      APPINSIGHTS_CONNECTIONSTRING: ${APPINSIGHTS_CONNECTIONSTRING}
      GATEWAY_HOST: ${GATEWAY_HOST:-http://localhost:3000}
      DATA_HOST: ${DATA_HOST:-http://ffc-sfd-data:3004/graphql}
      DEFRA_ID_ENABLED: ${DEFRA_ID_ENABLED:-false}
      DEFRA_ID_SIGN_OUT_ENABLED: ${DEFRA_ID_SIGN_OUT_ENABLED:-false}
      DEFRA_ID_WELL_KNOWN_URL: ${DEFRA_ID_WELL_KNOWN_URL}
      DEFRA_ID_CLIENT_ID: ${DEFRA_ID_CLIENT_ID}
      DEFRA_ID_CLIENT_SECRET: ${DEFRA_ID_CLIENT_SECRET}
      DEFRA_ID_SERVICE_ID: ${DEFRA_ID_SERVICE_ID}
      DEFRA_ID_POLICY: ${DEFRA_ID_POLICY}
      DEFRA_ID_REDIRECT_URL: ${DEFRA_ID_REDIRECT_URL:-http://localhost:3000/auth/sign-in-oidc}
      DEFRA_ID_POST_LOGOUT_REDIRECT_URL: ${DEFRA_ID_POST_LOGOUT_REDIRECT_URL:-http://localhost:3000/auth/sign-out-oidc}
      DEV_AUTH_PRIVATE_KEY: ${DEV_AUTH_PRIVATE_KEY}
      DEV_AUTH_PUBLIC_KEY: ${DEV_AUTH_PUBLIC_KEY}
      REDIS_HOST: ffc-sfd-auth-redis
      COOKIE_PASSWORD: the-password-must-be-at-least-32-characters-long

  ffc-sfd-auth-redis:
    image: redis:6.2.7
