# These are populated when your service is created via the ADP Portal scaffolder. Do not change these, as they are abstracted from your service and are mandatory. They are for your reference here.
name: ffc-sfd-auth
namespace: fcp-sfd
workstream: fcp-sfd
image: ffc-sfd-auth

# You may add further labels to identify the service or what your component does.
labels:
  component: backend

# Here you can define your Priority classes, min/max replicas etc. Empty block does the HELM Library defaults.
deployment: {}

# These may be changed. See here: https://github.com/DEFRA/adp-helm-library?tab=readme-ov-file#container-template
container:
  memCpuTier: L
  port: 3002

ingress:
  class: nginx
  endpoint: ffc-sfd
  server: example.com
  path: /auth

containerConfigMap:
  name: ffc-sfd-auth-config-map

secret:
  name: ffc-sfd-auth-container-secret
  type: Opaque

auth:
  defraIdEnabled: true
  defraIdWellKnownUrl: 
  defraIdClientId:
  defraIdClientSecret:
  defraIdServiceId:
  defraIdPolicy:
  defraIdRedirectPath: /auth/sign-in-oidc
  defraIdPostLogoutRedirectPath: /auth/sign-out-oidc
  devAuthPrivateKey:
  devAuthPublicKey:
  cookiePassword: the-password-must-be-at-least-32-characters-long

redis:
  host:
  port: 6380
  password:

livenessProbe:
  path: /auth/healthz
  port: 3002
  initialDelaySeconds: 20
  periodSeconds: 10
  failureThreshold: 3
  timeoutSeconds: 5

readinessProbe:
  path: /auth/healthy
  port: 3002
  initialDelaySeconds: 30
  periodSeconds: 10
  failureThreshold: 3
  timeoutSeconds: 5
