- key: APPINSIGHTS_CONNECTIONSTRING
  value: "{{servicename}}-APPINSIGHTS-CONNECTIONSTRING"
  type: "keyvault"
- key: REDIS_HOST
  value: "SNDADPINFRD3401.redis.cache.windows.net"
- key: REDIS_PASSWORD
  value: "{{servicename}}-REDIS-PASSWORD"
  type: "keyvault"
- key: GATEWAY_HOST
  value: "https://ffc-sfd-auth.snd3.adp.defra.gov.uk"
- key: DEFRA_ID_ENABLED
  value: "true"
- key: DEFRA_ID_SIGN_OUT_ENABLED
  value: "true"
- key: DEFRA_ID_WELL_KNOWN_URL
  value: "https://your-account.cpdev.cui.defra.gov.uk/idphub/b2c/b2c_1a_cui_cpdev_signupsigninsfi/.well-known/openid-configuration"
- key: DEFRA_ID_CLIENT_ID
  value: "{{servicename}}-DEFRA-ID-CLIENT-ID"
  type: "keyvault"
- key: DEFRA_ID_CLIENT_SECRET
  value: "{{servicename}}-DEFRA-ID-CLIENT-SECRET"
  type: "keyvault"
- key: DEFRA_ID_SERVICE_ID
  value: "{{servicename}}-DEFRA-ID-SERVICE-ID"
  type: "keyvault"
- key: DEFRA_ID_POLICY
  value: "b2c_1a_cui_cpdev_signupsigninsfi"
- key: DEFRA_ID_REDIRECT_URL
  value: "https://ffc-sfd-landing-page.snd3.adp.defra.gov.uk/auth/sign-in-oidc"
- key: DEFRA_ID_POST_LOGOUT_REDIRECT_URL
  value: "https://ffc-sfd-landing-page.snd3.adp.defra.gov.uk/auth/sign-out-oidc"
- key: COOKIE_PASSWORD
  value: "{{servicename}}-COOKIE-PASSWORD"
  type: "keyvault"
