- key: NODE_ENV
  value: "production"
- key: PORT
  value: "3002"
- key: APPINSIGHTS_CLOUDROLE
  value: "{{serviceName}}"
- key: REDIS_PORT
  value: "6380"
- key: DATA_HOST
  value: "http://ffc-sfd-data.fcp-sfd/graphql"
